### ISSUE TITLE
Bug founded

### ISSUE THREAD

**Issue by hicolazu** [ruby-formatter/rufo#185] opened 2019-10-15 16:24 UTC
I just had an error with my test code:
carro = Hash[nome: "Civic", marca: "Honda", cor: "Vermelho"]

config = Hash.new
config["ip"] = "3333.3333.3333.3333"
config["porta"] = 3333

puts "Seu ip: #{config["ip"]} está conectando na porta #{config["porta"]...}"

The error was: 
You've found a bug!
Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3554:in `bug': unexpected node:  at [[7, 76], :on_embexpr_end, "}", #<Ripper::Lexer::State: EXPR_BEG>] at [[7, 76], :on_embexpr_end, "}", #<Ripper::Lexer::State: EXPR_BEG>] (Rufo::Bug)
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:187:in `visit'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:2381:in `visit_range'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:426:in `visit'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:518:in `block (2 levels) in visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3671:in `push_node'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:517:in `block in visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `each'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `each_with_index'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:752:in `visit_string_interpolation'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:275:in `visit'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:518:in `block (2 levels) in visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3671:in `push_node'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:517:in `block in visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `each'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `each_with_index'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:688:in `block in visit_string_literal_end'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:677:in `with_unmodifiable_string_lines'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:687:in `visit_string_literal_end'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:614:in `visit_string_literal'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:236:in `visit'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1776:in `block (2 levels) in visit_comma_separated_list'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3451:in `maybe_indent'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1772:in `block in visit_comma_separated_list'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1771:in `each'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1771:in `each_with_index'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1771:in `visit_comma_separated_list'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1494:in `visit_call_args'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:349:in `visit'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:518:in `block (2 levels) in visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3671:in `push_node'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:517:in `block in visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `each'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `each_with_index'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1300:in `block in visit_command_args'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3359:in `indent'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1299:in `visit_command_args'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1183:in `block in visit_command_end'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3662:in `block (2 levels) in push_call'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3679:in `push_hash'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3661:in `block in push_call'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3671:in `push_node'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3658:in `push_call'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1182:in `visit_command_end'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:1178:in `visit_command'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:345:in `visit'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:518:in `block (2 levels) in visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3671:in `push_node'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:517:in `block in visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `each'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `each_with_index'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:496:in `visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:195:in `visit'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:173:in `format'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/command.rb:134:in `format'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/command.rb:49:in `format_stdin'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/command.rb:39:in `run'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/lib/rufo/command.rb:12:in `run'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.7.0/exe/rufo:4:in `<top (required)>'
	from C:/Ruby26-x64/bin/rufo:23:in `load'
	from C:/Ruby26-x64/bin/rufo:23:in `<main>'

**Comment by gingermusketeer** [comment] 2019-10-18 19:13
This is a duplicate of #183 which is now fixed.

**Closed by gingermusketeer** 2019-10-18 19:13 UTC
